### ISSUE TITLE
Graph DB Access Error

### ISSUE THREAD

**Issue by swallace21** [neo4j-examples/movies-golang-bolt#27]
Cloned the repo and ran:

`go run server.go`

`Running on port 8080, database is at neo4j+s://demo.neo4jlabs.com`

`error querying graph: Neo4jError: Neo.ClientError.Security.Forbidden (Database access is not allowed for user 'movies' with roles [PUBLIC, movies].)`

**Comment by fbiville** [comment]
Thanks for the report, it should be fixed now. It was due to a slight error when dealing with default configuration values.
